<x-app-layout>

    <div class="space-y-6">

        <div class="flex items-center justify-between">

            <div>
                <h1 class="text-3xl font-bold text-slate-900">
                    {{ Auth::user()->isTeknisi() ? 'Laporan Kerja' : 'Reports' }}
                </h1>

                <p class="mt-2 text-slate-500">
                    {{ Auth::user()->isTeknisi() ? 'Laporan aktivitas dan ringkasan pekerjaan maintenance.' : 'Generate and export hospital maintenance reports.' }}
                </p>
            </div>


            <a
                href="{{ route('reports.assets.pdf') }}"
                class="rounded-2xl bg-red-600 px-5 py-3 font-semibold text-white transition hover:bg-red-700">

                Export PDF

            </a>

        </div>

        <!-- Statistics -->

        <div class="bg-transparent">

            <div class="grid grid-cols-3 gap-6">

                <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">

                    <h2>Assets</h2>

                    <p class="mt-3 text-4xl font-bold">

                        {{ $assetCount }}

                    </p>

                </div>

                <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">

                    <h2>Tickets</h2>

                    <p class="mt-3 text-4xl font-bold">

                        {{ $ticketCount }}

                    </p>

                </div>

                <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">

                    <h2>Preventive</h2>

                    <p class="mt-3 text-4xl font-bold">

                        {{ $preventiveCount }}

                    </p>

                </div>

                <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">

                    <h2>Corrective</h2>

                    <p class="mt-3 text-4xl font-bold">

                        {{ $correctiveCount }}

                    </p>

                </div>

                <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">

                    <h2>Spareparts</h2>

                    <p class="mt-3 text-4xl font-bold">

                        {{ $sparepartCount }}

                    </p>

                </div>

                <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">

                    <h2>Vendors</h2>

                    <p class="mt-3 text-4xl font-bold">

                        {{ $vendorCount }}

                    </p>

                </div>

            </div>

        </div>

        <p class="mt-8 text-center text-sm text-slate-400">
            Generated by Hospital CMMS • {{ date('Y') }}
        </p>

    </div>

</x-app-layout>